# -*- coding: utf-8 -*-
"""Salary prediction2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyNHtysZAFB7WMrQjKd--efLgulPKHBa
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import pickle

saldf=pd.read_csv('/content/Salary Data.csv')

saldf.head()

LR=LinearRegression()

saldf.isnull().sum()

saldf.dropna(inplace=True)

saldf.isnull().sum()

from sklearn.preprocessing import LabelEncoder
x=LabelEncoder()
y=LabelEncoder()
saldf['Gen_new']=x.fit_transform(saldf['Gender'])
saldf['Edu_new']=y.fit_transform(saldf['Education Level'])

a=saldf[['Years of Experience']]
b=saldf['Salary']

LR.fit(a,b)

with open('Salary Prediction.pkl','wb') as f:
  pickle.dump(LR,f)
print("model")

LR.predict([[5]])

